version: "3.7"
services:
  nginx1:
    image: nginx1
    build: nginx1
    ports:
      - "8081:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 5s
      retries: 3
      timeout: 2s
      start_period: 5s
  nginx2:
    image: nginx2
    build: nginx2
    ports:
      - "8082:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 5s
      retries: 3
      timeout: 2s
      start_period: 5s
  nginx3:
    image: nginx3
    build: nginx3
    ports:
      - "8083:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083"]
      interval: 5s
      retries: 3
      timeout: 2s
      start_period: 5s
  reverse-proxy:
    image: reverse-proxy
    build: reverse-proxy
    ports:
      - "8080:80"
    depends_on:
      - nginx1
      - nginx2
      - nginx3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      retries: 3
      timeout: 2s
      start_period: 5s
